alias tmux='tmux -2'
alias gst='git status'
alias glo='git log'
alias gd='git add'
alias gp='git pull'
alias gpr='git pull --rebase'
alias gpu='git push'
alias gpuf='git push -f'
alias gc='git commit'
alias gca='git commit --amend --no-edit --no-verify'
alias gco='git checkout'
alias grm='git rebase main'
alias grm='git rebase --continue'
alias gnb="gco -b"
alias ggraph="git log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold cyan)%aD%C(reset) %C(bold green)(%ar)%C(reset)%C(bold yellow)%d%C(reset)%n''          %C(white)%s%C(reset) %C(dim white)- %an%C(reset)' --all"
alias scala="/Users/step12/Downloads/scala-2.13.1/bin/scala"
alias latest="nvm use latest"
alias stable="nvm use stable"
alias cr="~/customCommand/cr.sh"
alias clr="~/customCommand/clr.sh"
alias grep="grep --color"
alias dra="docker run --dns 10.21.21.226 --dns 172.16.2.220 -v /Users/rivulayek/myfiles/project/android/:/repos:rw -v /Users/rivulayek/dotfilesR:/dotfiles:rw --rm -it income-codecommit /bin/bash"
alias py="python3"
